### ISSUE TITLE
Add dataset on-boarding date and freshness score

### ISSUE THREAD

**Issue by wleepang** [awslabs/open-data-registry-browser#113]
Good metadata to have would be:

1. when an dataset was first published on the registry
2. when a dataset was last updated (or some other metric of freshness)

The first provides a view into the longevity of a dataset and is a proxy for how long a class of datasets has been available in the registry.  The second provides users with a gauge for the utility of a dataset relative to currently available tooling and integration with other datasets.

**Comment by zflamig** [comment]
Hi @wleepang 

We have 2 metadata fields in the hosted yaml files now.

For example: https://registry.opendata.aws/datasets/awslabs-open-data-registry/datasets/1000-genomes.yaml

You will find
```
RegistryEntryAdded: "2018-04-17"
RegistryEntryLastModified: "2019-08-16"
```

Are these what you are looking for?

**Comment by wleepang** [comment]
Ah, the `RegistryEntryAdded` is good. Is there a way to expose these on the rendered dataset listing?

Re: `RegistryEntryLastModified` - this refers to contents in the dataset's `.yaml` file correct?

Is it feasible to do a summary `ls` on a dataset to check for most recent modification date with each registry release?

**Comment by zflamig** [comment]
@jedsundwall Had opinions on not rendering them and potentially confusing users. Tagging him here so he can chime in.

Some of the buckets are huge (100s of millions of objects), do you know a fast way to get the last modified date? I think we viewed it as potentially too time consuming to include here.

**Comment by jedsundwall** [comment]
I'm not inclined to display dates showing when datasets were added to the registry because it may be misunderstood as being relevant to the data itself.

Also, even if we could assess the recency of objects in buckets (`ls` would likely be expensive, as @zflamig points out), I wouldn't want to do it because it might give the impression that recency is an inherently good quality for a dataset. Some of our datasets are updated on a per-second basis and others have never been updated since being uploaded. I don't want to give the impression that a dataset might be stale when it's not.

Having said all that, @wleepang, note that we do publish http://registry.opendata.aws/change-log/ where you can see when datasets have been added to the registry – we just don't show this data in the registry listing itself.

**Comment by wleepang** [comment]
All valid points. I'm good with the status quo then.
